#ifndef CONFIG_USER_H
#define CONFIG_USER_H

#include "config_common.h"

#define USE_SERIAL

#define MASTER_LEFT

#define MOUSEKEY_DELAY 0
#define MOUSEKEY_DELTA 5
#define MOUSEKEY_INTERVAL 0
#define MOUSEKEY_MAX_SPEED 3
#define MOUSEKEY_TIME_TO_MAX 120

#define TAPPING_TERM 150

#undef RGBLED_NUM
#define RGBLIGHT_ANIMATIONS
#define RGBLED_NUM 12
#define RGBLIGHT_HUE_STEP 8
#define RGBLIGHT_SAT_STEP 8
#define RGBLIGHT_VAL_STEP 8

#endif
